[pyprland]
plugins = ["shortcuts_menu", "toggle_special"]

# using variables for demonstration purposes (not needed)
[pyprland.variables]
float_term = "kitty --class float-win --"
float_term_c = "kitty --class float-win"

# [scratchpads.term]
# animation = ""
# command = "kitty --class kitty-scratchpad"
# class = "kitty-scratchpad"
# size = "60% 70%"
# max_size = "1920px 100%"
# position = "20% 15%"
# offset = "130%"
# hide_delay = 0

# [monitors]
# hotplug_command = "./scripts/setup-monitors.sh; hyprctl reload; pgrep ags || (ags -q && ags); hyprctl notify 5 3000 0 'Configured monitors'"
# unknown = "./scripts/setup-monitors.sh; hyprctl reload; pgrep ags || (ags -q && ags); hyprctl notify 5 3000 0 'Configured monitors'"

# [monitors.placement]
# "LG Electronics LG FHD".leftOf = "eDP-1"


[shortcuts_menu]
engine = "tofi"
parameters = ""

[shortcuts_menu.entries]
# "hyprprop" = "kitty -- sh -c 'hyprprop; read'"
"hyprprop" = "[float_term_c] --title hyprprop -- sh -c 'hyprprop; read -rsn1'"
"bpytop" = "[float_term_c] --title bpytop bpytop"
"xwininfo" = "[float_term] sh -c 'xwininfo; read'"
"View keybinds" = "[float_term] sh -c 'micro $HYPR_CONFIG/hyprland/keybinds.conf'"
"View commands" = "[float_term] sh -c 'micro $HOME/commands.txt'"
"View configs" = "code ~/personal/config.code-workspace"

"Hyprland socket" = 'kitty socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"'
"Hyprland logs" = 'kitty tail -f $XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/hyprland.log'

"Color picker" = [
    { name = "format", options = [
        "hex",
        "rgb",
        "hsv",
        "hsl",
        "cmyk",
    ] },
    "sleep 0.2; hyprpicker --format [format] | wl-copy", # sleep to let the menu close before the picker opens
]

