"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 2
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'lightBlue'
    template = '# '

  [[blocks.segments]]
    type = 'root'
    style = 'plain'
    foreground = 'red'
    template = ' % '

  [[blocks.segments]]
    type = 'session'
    style = 'plain'
    template = '<cyan>{{ .UserName }}</><darkGray>@</><green>{{ .HostName }}</> '

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    foreground = 'lightYellow'
    template = '<darkGray>in </>{{ .Path }} '

    [blocks.segments.properties]
      style = 'powerlevel'

  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    # template = '<darkGray>on</> <white>git:</><cyan>{{ .HEAD }}</>{{ if .Working.Changed }}<red> x</>{{ end }} '
	template = '<darkGray>on</> <white>{{ .UpstreamIcon }}</><cyan{{ .HEAD }}</>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}'
	
    [blocks.segments.properties]
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'status'
    style = 'plain'
    foreground = 'red'
    template = ' C:{{ if gt .Code 0 }}{{ .Code }}{{ end }} '
    
  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    template = "<darkGray>took</> <white>{{ .FormattedMs }}</>"
    
[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'python'
    style = 'plain'
    foreground = 'white'
    template = '({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ .Full }}{{ end }})'

    [blocks.segments.properties]
      fetch_version = false
    
  [[blocks.segments]]
    type = 'java'
    style = 'plain'
    foreground = '#f89820'
    template = '<white>(</>{{ if .Error }}{{ .Error }}{{ else }} {{ .Full }}{{ end }}<white>)</>'
  
  [[blocks.segments]]
    type = 'node'
    style = 'plain'
    template = '<white>(</>{{ if glob "bun.lockb" }}<#faefde>🥟 {{ .Full }}</>{{ else }}<#6cc24a> {{ .Full }}</>{{ end }}<white>)</>'
    
  [[blocks.segments]]
    type = 'dotnet'
    style = 'plain'
    foreground = '#4122aa'
    template = '<white>(</>{{ if .Unsupported }}{{ .Unsupported }}{{ else }} {{ .Full }}{{ end }}<white>)</>'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = 'lightCyan'
    template = '$'
