version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = '# '
    foreground = 'lightBlue'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = ' % '
    foreground = 'red'
    type = 'root'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<cyan>{{ .UserName }}</><darkGray>@</><green>{{ .HostName }}</> '
    type = 'session'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<darkGray>in </>{{ .Path }} '
    foreground = 'lightYellow'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'powerlevel'

  [[blocks.segments]]
    template = '<darkGray>on</> <white>{{ .UpstreamIcon }}: </><cyan>{{ .HEAD }}</>{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = 'C:{{ if gt .Code 0 }}{{ .Code }}{{ end }} '
    foreground = 'red'
    type = 'status'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<darkGray>took</> <white>{{ .FormattedMs }}</>'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  overflow = 'hidden'

  [[blocks.segments]]
    template = '({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ .Full }}{{ end }})'
    foreground = 'white'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      fetch_version = false

  [[blocks.segments]]
    template = '<white>(</>{{ if .Error }}{{ .Error }}{{ else }} {{ .Full }}{{ end }}<white>)</>'
    foreground = '#f89820'
    type = 'java'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<white>(</>{{ if glob "bun.lockb" }}<#faefde>🥟 {{ .Full }}</>{{ else }}<#6cc24a> {{ .Full }}</>{{ end }}<white>)</>'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

  [[blocks.segments]]
    template = '<white>(</>{{ if .Unsupported }}{{ .Unsupported }}{{ else }} {{ .Full }}{{ end }}<white>)</>'
    foreground = '#4122aa'
    type = 'dotnet'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '$'
    foreground = 'lightCyan'
    type = 'text'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
